Bearlyml23 and robo23
ucb-bar/Baremetal-IDE-bsp pull request #11
Opened 2023-10-17 18:27 UTC by jasonkimsoso

robo23 and bearlyml23 setup

2023-10-19 17:18 UTC, T-K-233 commented on bearlyml23/bearlyml23.ld
> +  SCRATCH  (rwx): ORIGIN = 0x08000000, LENGTH = 16K
Scratchpad should be 64K?

2023-10-19 17:19 UTC, T-K-233 commented on bearlyml23/inc/bearlyml23.h
> +  __IO uint32_t MSIP3;                          /** MSIP Registers (1 bit wide) */
I helped you fix this. Bearlyml23 has only 4 cores, so there's only MSIP[0..3] registers

2023-10-19 17:21 UTC, T-K-233 commented on bearlyml23/inc/bearlyml23.h
> +  __IO uint32_t TILE0_RESET;      /** RocketTile 0 */   // 0x00
Make sure the RCC (Reset and Clock Control) are correct. Do we still have reset and clock gate for all cores? How many cores are there?

2023-10-19 17:22 UTC, T-K-233 commented on robo23/inc/robo23.h
> +  __IO uint32_t TILE0_RESET;      /** RocketTile 0 */   // 0x00
Same here as bearlyml23

2023-10-19 17:22 UTC, T-K-233 requested changes
Thanks!
Generally looks good. There's some small bugs that need to be fixed.

2023-10-19 19:49 UTC, jasonkimsoso commented
Sorry about that. I didn't know PR automatically update the new commits.

2023-11-09 22:25 UTC, T-K-233 approved these changes
Looks good.

2023-11-09 22:26 UTC, merged